import React, { useState } from 'react';
import {
  DoorOpen,
  Calendar,
  Tag,
  Activity,
  TrendingUp,
  MessageSquare,
  Target,
  ExternalLink,
  ChevronDown,
  ChevronUp,
  Info
} from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from './ui/card';
import { Badge } from './ui/badge';
import { Button } from './ui/button';
import { Tabs, TabsContent, TabsList, TabsTrigger } from './ui/tabs';
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from './ui/collapsible';

/**
 * DoorDetail - Full Door Information Display
 * 
 * Features:
 * - Full door description and purpose
 * - Linked tensions that led to this door
 * - Questions to ask (generated by AI)
 * - Signals that suggest walking through this door
 * - Timeline of door creation/evolution
 * - User notes and reflections related to this door
 * 
 * Constitutional Note: Doors are invitations, not instructions.
 * They suggest paths based on patterns, but your journey is yours to choose.
 */

interface TensionSummary {
  id: string;
  label: string;
  energy: number;
}

interface DoorQuestion {
  id: string;
  text: string;
  category: 'reflection' | 'action' | 'exploration';
}

interface DoorSignal {
  id: string;
  type: 'posture_shift' | 'tension_spike' | 'lens_pattern' | 'reflection_theme';
  description: string;
  detected: string;
}

interface DoorNote {
  id: string;
  content: string;
  createdAt: string;
}

interface DoorEvent {
  id: string;
  type: 'created' | 'walked' | 'questioned' | 'noted';
  description: string;
  timestamp: string;
}

interface Door {
  id: string;
  label: string;
  description: string;
  purpose: string;
  state: 'open' | 'walked' | 'suggested';
  linkedTensions: TensionSummary[];
  questions: DoorQuestion[];
  signals: DoorSignal[];
  notes: DoorNote[];
  timeline: DoorEvent[];
  createdAt: string;
  lastUpdated: string;
  walkedAt?: string;
  lensTags: string[];
}

interface DoorDetailProps {
  door: Door;
  onWalkThrough?: (doorId: string) => void;
  onAddNote?: (doorId: string, note: string) => void;
  onViewTension?: (tensionId: string) => void;
}

// State colors
const stateStyles = {
  open: { color: 'text-emerald-700', bg: 'bg-emerald-100', border: 'border-emerald-500' },
  walked: { color: 'text-blue-700', bg: 'bg-blue-100', border: 'border-blue-500' },
  suggested: { color: 'text-amber-700', bg: 'bg-amber-100', border: 'border-amber-500' }
};

// Question category icons/colors
const questionStyles = {
  reflection: { icon: MessageSquare, color: 'text-purple-600', bg: 'bg-purple-50' },
  action: { icon: Target, color: 'text-emerald-600', bg: 'bg-emerald-50' },
  exploration: { icon: TrendingUp, color: 'text-blue-600', bg: 'bg-blue-50' }
};

// Signal type icons
const signalIcons = {
  posture_shift: Activity,
  tension_spike: TrendingUp,
  lens_pattern: Tag,
  reflection_theme: MessageSquare
};

export function DoorDetail({
  door,
  onWalkThrough,
  onAddNote,
  onViewTension
}: DoorDetailProps) {
  const [showAllQuestions, setShowAllQuestions] = useState(false);
  const [showAllSignals, setShowAllSignals] = useState(false);
  const [noteInput, setNoteInput] = useState('');
  const styles = stateStyles[door.state];

  const visibleQuestions = showAllQuestions ? door.questions : door.questions.slice(0, 3);
  const visibleSignals = showAllSignals ? door.signals : door.signals.slice(0, 3);

  const handleAddNote = () => {
    if (noteInput.trim() && onAddNote) {
      onAddNote(door.id, noteInput.trim());
      setNoteInput('');
    }
  };

  return (
    <div className="space-y-6">
      {/* Header Card */}
      <Card className={`border-l-4 ${styles.border}`}>
        <CardHeader>
          <div className="flex items-start justify-between">
            <div className="space-y-2">
              <div className="flex items-center gap-3">
                <DoorOpen className={`h-6 w-6 ${styles.color}`} />
                <CardTitle className="text-2xl">{door.label}</CardTitle>
              </div>
              <Badge className={`${styles.bg} ${styles.color} border-0`}>
                {door.state.charAt(0).toUpperCase() + door.state.slice(1)}
              </Badge>
            </div>
            {door.state === 'open' && onWalkThrough && (
              <Button
                onClick={() => onWalkThrough(door.id)}
                className="flex items-center gap-2"
              >
                <DoorOpen className="h-4 w-4" />
                Walk Through This Door
              </Button>
            )}
          </div>
        </CardHeader>

        <CardContent className="space-y-4">
          {/* Description */}
          <div>
            <h3 className="font-semibold text-gray-900 mb-2">What This Door Is</h3>
            <p className="text-gray-700">{door.description}</p>
          </div>

          {/* Purpose */}
          <div className="p-4 bg-blue-50 border border-blue-200 rounded-lg">
            <div className="flex items-start gap-3">
              <Info className="h-5 w-5 text-blue-600 mt-0.5 flex-shrink-0" />
              <div>
                <h4 className="font-semibold text-blue-900 mb-1">Purpose</h4>
                <p className="text-sm text-blue-800">{door.purpose}</p>
              </div>
            </div>
          </div>

          {/* Metadata */}
          <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
            <div className="flex items-center gap-2 text-sm">
              <Calendar className="h-4 w-4 text-gray-500" />
              <div>
                <p className="text-xs text-gray-500">Created</p>
                <p className="font-medium">{new Date(door.createdAt).toLocaleDateString()}</p>
              </div>
            </div>
            <div className="flex items-center gap-2 text-sm">
              <Activity className="h-4 w-4 text-gray-500" />
              <div>
                <p className="text-xs text-gray-500">Last Updated</p>
                <p className="font-medium">{new Date(door.lastUpdated).toLocaleDateString()}</p>
              </div>
            </div>
            {door.walkedAt && (
              <div className="flex items-center gap-2 text-sm">
                <DoorOpen className="h-4 w-4 text-gray-500" />
                <div>
                  <p className="text-xs text-gray-500">Walked</p>
                  <p className="font-medium">{new Date(door.walkedAt).toLocaleDateString()}</p>
                </div>
              </div>
            )}
          </div>

          {/* Lens Tags */}
          {door.lensTags.length > 0 && (
            <div>
              <div className="flex items-center gap-2 mb-2">
                <Tag className="h-4 w-4 text-gray-500" />
                <span className="text-sm font-medium text-gray-700">Related Lenses</span>
              </div>
              <div className="flex flex-wrap gap-2">
                {door.lensTags.map(tag => (
                  <Badge key={tag} variant="outline" className="text-xs">
                    {tag}
                  </Badge>
                ))}
              </div>
            </div>
          )}
        </CardContent>
      </Card>

      {/* Tabbed Content */}
      <Tabs defaultValue="questions" className="space-y-4">
        <TabsList className="grid w-full grid-cols-4">
          <TabsTrigger value="questions">
            Questions ({door.questions.length})
          </TabsTrigger>
          <TabsTrigger value="tensions">
            Tensions ({door.linkedTensions.length})
          </TabsTrigger>
          <TabsTrigger value="signals">
            Signals ({door.signals.length})
          </TabsTrigger>
          <TabsTrigger value="timeline">
            Timeline ({door.timeline.length})
          </TabsTrigger>
        </TabsList>

        {/* Questions Tab */}
        <TabsContent value="questions" className="space-y-3">
          <Card>
            <CardHeader>
              <CardTitle className="text-lg">Questions to Ask</CardTitle>
              <p className="text-sm text-gray-500">
                These questions can help you explore what this door represents
              </p>
            </CardHeader>
            <CardContent className="space-y-3">
              {visibleQuestions.map(question => {
                const style = questionStyles[question.category];
                const Icon = style.icon;
                return (
                  <div
                    key={question.id}
                    className={`p-4 ${style.bg} border border-gray-200 rounded-lg`}
                  >
                    <div className="flex items-start gap-3">
                      <Icon className={`h-5 w-5 ${style.color} mt-0.5 flex-shrink-0`} />
                      <div className="flex-1">
                        <p className="text-gray-900">{question.text}</p>
                        <Badge variant="outline" className="mt-2 text-xs">
                          {question.category}
                        </Badge>
                      </div>
                    </div>
                  </div>
                );
              })}
              {door.questions.length > 3 && (
                <Button
                  variant="ghost"
                  onClick={() => setShowAllQuestions(!showAllQuestions)}
                  className="w-full"
                >
                  {showAllQuestions ? (
                    <>
                      <ChevronUp className="h-4 w-4 mr-2" />
                      Show Less
                    </>
                  ) : (
                    <>
                      <ChevronDown className="h-4 w-4 mr-2" />
                      Show {door.questions.length - 3} More Questions
                    </>
                  )}
                </Button>
              )}
            </CardContent>
          </Card>
        </TabsContent>

        {/* Tensions Tab */}
        <TabsContent value="tensions" className="space-y-3">
          <Card>
            <CardHeader>
              <CardTitle className="text-lg">Linked Tensions</CardTitle>
              <p className="text-sm text-gray-500">
                Tensions that led to this door being suggested
              </p>
            </CardHeader>
            <CardContent className="space-y-2">
              {door.linkedTensions.map(tension => (
                <button
                  key={tension.id}
                  onClick={() => onViewTension?.(tension.id)}
                  className="w-full p-4 bg-gray-50 hover:bg-gray-100 rounded-lg transition-colors flex items-center justify-between group"
                >
                  <div className="flex items-center gap-3">
                    <TrendingUp className="h-5 w-5 text-purple-600" />
                    <span className="font-medium text-left">{tension.label}</span>
                  </div>
                  <div className="flex items-center gap-3">
                    <div className="flex items-center gap-2">
                      <div className="h-2 w-16 bg-gray-200 rounded-full overflow-hidden">
                        <div
                          className="h-full bg-purple-500"
                          style={{ width: `${tension.energy * 100}%` }}
                        />
                      </div>
                      <span className="text-sm text-gray-500">
                        {(tension.energy * 100).toFixed(0)}%
                      </span>
                    </div>
                    {onViewTension && (
                      <ExternalLink className="h-4 w-4 text-gray-400 group-hover:text-gray-600" />
                    )}
                  </div>
                </button>
              ))}
            </CardContent>
          </Card>
        </TabsContent>

        {/* Signals Tab */}
        <TabsContent value="signals" className="space-y-3">
          <Card>
            <CardHeader>
              <CardTitle className="text-lg">Detection Signals</CardTitle>
              <p className="text-sm text-gray-500">
                Patterns that suggested this door might be relevant
              </p>
            </CardHeader>
            <CardContent className="space-y-2">
              {visibleSignals.map(signal => {
                const Icon = signalIcons[signal.type];
                return (
                  <div
                    key={signal.id}
                    className="p-3 bg-gray-50 border border-gray-200 rounded-lg"
                  >
                    <div className="flex items-start gap-3">
                      <Icon className="h-5 w-5 text-gray-600 mt-0.5" />
                      <div className="flex-1">
                        <p className="text-sm text-gray-900">{signal.description}</p>
                        <p className="text-xs text-gray-500 mt-1">
                          Detected {new Date(signal.detected).toLocaleDateString()}
                        </p>
                      </div>
                    </div>
                  </div>
                );
              })}
              {door.signals.length > 3 && (
                <Button
                  variant="ghost"
                  onClick={() => setShowAllSignals(!showAllSignals)}
                  className="w-full"
                >
                  {showAllSignals ? (
                    <>
                      <ChevronUp className="h-4 w-4 mr-2" />
                      Show Less
                    </>
                  ) : (
                    <>
                      <ChevronDown className="h-4 w-4 mr-2" />
                      Show {door.signals.length - 3} More Signals
                    </>
                  )}
                </Button>
              )}
            </CardContent>
          </Card>
        </TabsContent>

        {/* Timeline Tab */}
        <TabsContent value="timeline" className="space-y-3">
          <Card>
            <CardHeader>
              <CardTitle className="text-lg">Door Timeline</CardTitle>
              <p className="text-sm text-gray-500">
                History of this door's creation and your interactions
              </p>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                {door.timeline.map((event, index) => (
                  <div key={event.id} className="flex gap-4">
                    <div className="flex flex-col items-center">
                      <div className={`h-3 w-3 rounded-full ${
                        event.type === 'created' ? 'bg-blue-500' :
                        event.type === 'walked' ? 'bg-emerald-500' :
                        event.type === 'questioned' ? 'bg-purple-500' :
                        'bg-gray-500'
                      }`} />
                      {index < door.timeline.length - 1 && (
                        <div className="h-full w-px bg-gray-200" />
                      )}
                    </div>
                    <div className="flex-1 pb-4">
                      <p className="font-medium text-gray-900">{event.description}</p>
                      <p className="text-sm text-gray-500">
                        {new Date(event.timestamp).toLocaleString()}
                      </p>
                    </div>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>

      {/* Notes Section */}
      <Card>
        <CardHeader>
          <CardTitle className="text-lg">Your Notes</CardTitle>
          <p className="text-sm text-gray-500">
            Personal reflections about this door
          </p>
        </CardHeader>
        <CardContent className="space-y-4">
          {/* Existing Notes */}
          {door.notes.length > 0 ? (
            <div className="space-y-3">
              {door.notes.map(note => (
                <div key={note.id} className="p-3 bg-gray-50 border border-gray-200 rounded-lg">
                  <p className="text-sm text-gray-900">{note.content}</p>
                  <p className="text-xs text-gray-500 mt-2">
                    {new Date(note.createdAt).toLocaleString()}
                  </p>
                </div>
              ))}
            </div>
          ) : (
            <p className="text-sm text-gray-500 italic">No notes yet</p>
          )}

          {/* Add Note */}
          {onAddNote && (
            <div className="space-y-2">
              <textarea
                value={noteInput}
                onChange={(e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => setNoteInput(e.target.value)}
                placeholder="Add a note about this door..."
                className="w-full p-3 border border-gray-300 rounded-lg resize-none focus:ring-2 focus:ring-purple-500 focus:border-transparent"
                rows={3}
              />
              <div className="flex justify-between items-center">
                <span className="text-xs text-gray-500">
                  {noteInput.length} / 500
                </span>
                <Button
                  onClick={handleAddNote}
                  disabled={noteInput.trim().length === 0 || noteInput.length > 500}
                  size="sm"
                >
                  Add Note
                </Button>
              </div>
            </div>
          )}
        </CardContent>
      </Card>

      {/* Constitutional Note */}
      <Card className="bg-purple-50 border-purple-200">
        <CardContent className="pt-6">
          <p className="text-sm text-purple-900">
            <strong>Doors are invitations, not instructions.</strong> They represent 
            potential paths based on patterns in your reflections—but whether to walk 
            through them is entirely your choice. Some doors may never be walked, and 
            that's perfectly fine. Your journey is yours to navigate.
          </p>
        </CardContent>
      </Card>
    </div>
  );
}

/**
 * Usage Example:
 * 
 * <DoorDetail
 *   door={{
 *     id: 'door_123',
 *     label: 'Exploring Boundary-Setting',
 *     description: 'A door that opened when patterns around saying "no" emerged...',
 *     purpose: 'Help you explore how you set (or don\'t set) boundaries in relationships',
 *     state: 'open',
 *     linkedTensions: [
 *       { id: 't1', label: 'Want to help vs. feeling drained', energy: 0.82 }
 *     ],
 *     questions: [
 *       {
 *         id: 'q1',
 *         text: 'When do you find it hardest to say no?',
 *         category: 'reflection'
 *       }
 *     ],
 *     signals: [
 *       {
 *         id: 's1',
 *         type: 'tension_spike',
 *         description: 'High tension between helping others and self-care',
 *         detected: '2024-01-10T00:00:00Z'
 *       }
 *     ],
 *     notes: [],
 *     timeline: [
 *       {
 *         id: 'e1',
 *         type: 'created',
 *         description: 'Door created by MirrorX',
 *         timestamp: '2024-01-10T00:00:00Z'
 *       }
 *     ],
 *     createdAt: '2024-01-10T00:00:00Z',
 *     lastUpdated: '2024-01-15T00:00:00Z',
 *     lensTags: ['relationships', 'boundaries', 'self-care']
 *   }}
 *   onWalkThrough={(id) => console.log('Walk through:', id)}
 *   onAddNote={(id, note) => console.log('Add note:', note)}
 *   onViewTension={(id) => console.log('View tension:', id)}
 * />
 */

