import React, { useState } from 'react';
import { Copy, CheckCircle, ThumbsUp, ThumbsDown, Bot, User } from 'lucide-react';
import { Card, CardContent, CardHeader } from './ui/card';
import { Badge } from './ui/badge';
import { Button } from './ui/button';

/**
 * MirrorBackDisplay - AI Response Component
 * 
 * Displays AI mirrorbacks with:
 * - Source indicator (ai/human)
 * - Tone visualization
 * - Feedback buttons (helpful/unhelpful)
 * - Copy to clipboard
 * 
 * Constitutional Note: Transparency about AI vs. human responses
 * is critical for informed user experience.
 */

interface MirrorBackDisplayProps {
  mirrorbackId: string;
  content: string;
  source: 'ai' | 'human';
  tone?: 'raw' | 'processing' | 'clear';
  createdAt: string;
  authorUsername?: string; // For human mirrorbacks
  onFeedback?: (mirrorbackId: string, isHelpful: boolean) => void;
  userFeedback?: boolean | null; // null = no feedback yet, true = helpful, false = unhelpful
}

export function MirrorBackDisplay({
  mirrorbackId,
  content,
  source,
  tone = 'clear',
  createdAt,
  authorUsername,
  onFeedback,
  userFeedback = null
}: MirrorBackDisplayProps) {
  const [copied, setCopied] = useState(false);

  // Tone colors
  const toneColors = {
    raw: 'text-amber-600 bg-amber-50 border-amber-200',
    processing: 'text-blue-600 bg-blue-50 border-blue-200',
    clear: 'text-emerald-600 bg-emerald-50 border-emerald-200'
  };

  // Tone descriptions
  const toneDescriptions = {
    raw: 'Unfiltered, direct response',
    processing: 'Thinking through complexity',
    clear: 'Synthesized understanding'
  };

  // Copy to clipboard
  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(content);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Failed to copy:', err);
    }
  };

  // Handle feedback
  const handleFeedback = (isHelpful: boolean) => {
    if (onFeedback) {
      onFeedback(mirrorbackId, isHelpful);
    }
  };

  // Format timestamp
  const formatTime = (dateString: string) => {
    const date = new Date(dateString);
    const now = new Date();
    const diffMs = now.getTime() - date.getTime();
    const diffMins = Math.floor(diffMs / 60000);
    
    if (diffMins < 1) return 'just now';
    if (diffMins < 60) return `${diffMins}m ago`;
    
    const diffHours = Math.floor(diffMins / 60);
    if (diffHours < 24) return `${diffHours}h ago`;
    
    const diffDays = Math.floor(diffHours / 24);
    if (diffDays < 7) return `${diffDays}d ago`;
    
    return date.toLocaleDateString();
  };

  return (
    <Card className="border-l-4 border-l-purple-500">
      <CardHeader className="pb-3">
        <div className="flex items-center justify-between">
          {/* Source Indicator */}
          <div className="flex items-center gap-2">
            {source === 'ai' ? (
              <>
                <Bot className="h-5 w-5 text-purple-600" />
                <span className="font-medium text-sm text-purple-600">MirrorX Intelligence</span>
              </>
            ) : (
              <>
                <User className="h-5 w-5 text-blue-600" />
                <span className="font-medium text-sm text-blue-600">
                  {authorUsername ? `@${authorUsername}` : 'Guide Response'}
                </span>
              </>
            )}
            <Badge variant="outline" className="ml-2">
              {source === 'ai' ? 'AI' : 'Human'}
            </Badge>
          </div>

          {/* Timestamp */}
          <span className="text-xs text-gray-500">{formatTime(createdAt)}</span>
        </div>

        {/* Tone Indicator */}
        {tone && (
          <div className="mt-2">
            <Badge 
              variant="outline" 
              className={`${toneColors[tone]} text-xs`}
            >
              Tone: {tone} — {toneDescriptions[tone]}
            </Badge>
          </div>
        )}
      </CardHeader>

      <CardContent className="space-y-4">
        {/* Mirrorback Content */}
        <div className="prose prose-sm max-w-none">
          <p className="text-gray-800 whitespace-pre-wrap leading-relaxed">
            {content}
          </p>
        </div>

        {/* Constitutional Note */}
        {source === 'ai' && (
          <div className="text-xs text-gray-500 italic border-l-2 border-gray-300 pl-3 py-2">
            This reflection was generated by AI based on your input. 
            It's here to mirror possibilities, not to judge or prescribe. 
            You're always in control of what resonates.
          </div>
        )}

        {/* Action Bar */}
        <div className="flex items-center justify-between pt-4 border-t">
          {/* Feedback Buttons */}
          <div className="flex items-center gap-2">
            <span className="text-xs text-gray-600 mr-2">Was this helpful?</span>
            
            <Button
              variant={userFeedback === true ? 'default' : 'outline'}
              size="sm"
              onClick={() => handleFeedback(true)}
              className="flex items-center gap-1"
              disabled={userFeedback !== null}
            >
              <ThumbsUp className="h-4 w-4" />
              Helpful
            </Button>

            <Button
              variant={userFeedback === false ? 'default' : 'outline'}
              size="sm"
              onClick={() => handleFeedback(false)}
              className="flex items-center gap-1"
              disabled={userFeedback !== null}
            >
              <ThumbsDown className="h-4 w-4" />
              Unhelpful
            </Button>

            {userFeedback !== null && (
              <span className="text-xs text-green-600 ml-2">
                Thanks for your feedback!
              </span>
            )}
          </div>

          {/* Copy Button */}
          <Button
            variant="ghost"
            size="sm"
            onClick={handleCopy}
            className="flex items-center gap-1"
          >
            {copied ? (
              <>
                <CheckCircle className="h-4 w-4 text-green-600" />
                <span className="text-green-600">Copied!</span>
              </>
            ) : (
              <>
                <Copy className="h-4 w-4" />
                Copy
              </>
            )}
          </Button>
        </div>

        {/* Feedback Explainer */}
        {userFeedback === false && (
          <div className="text-xs text-gray-600 bg-amber-50 border border-amber-200 rounded-lg p-3">
            <strong>Your feedback helps us evolve:</strong> We use "unhelpful" signals to 
            identify patterns in delivery timing, tone mismatches, and content gaps. 
            This doesn't affect the content itself—only when and how we surface insights.
          </div>
        )}
      </CardContent>
    </Card>
  );
}

/**
 * Usage Example:
 * 
 * <MirrorBackDisplay
 *   mirrorbackId="mb_123"
 *   content="I notice you're wrestling with two conflicting desires: wanting connection while needing space. This tension isn't something to resolve—it's information about where you are right now."
 *   source="ai"
 *   tone="clear"
 *   createdAt="2024-01-15T10:30:00Z"
 *   onFeedback={(id, helpful) => console.log(`Feedback: ${helpful}`)}
 *   userFeedback={null}
 * />
 */
