-- ============================================================================
-- The Mirror Platform — 0013 seed: the lexicon shells (P6 / §A·§B)
-- GENERATED from supabase/seed/lexicon-seed.json by scripts/gen-seed-sql.mjs.
-- Do not edit by hand; re-run the generator. Idempotent (upsert / coalesce).
--
-- The §A term records + the §B requires-DAG. TEACH first_glosses are PLACEHOLDERS
-- copied verbatim (authored by A Reflection under the AI-prose ban §17) — an
-- existing authored gloss is never clobbered (coalesce). The acyclicity trigger
-- (0006) validates every requires edge on insert.
-- ============================================================================
begin;

insert into term (term,surface_forms,register,our_meaning,defines_node,reader_assumptions,
                  collision,disposition,plain,first_gloss,tier0,arrival_early,gloss_verdict,gloss_refuter,notes) values
  ('encounter',ARRAY['encounter','encountered']::text[],'transmission','meeting what you did not author; the only thing that settles a verdict','B1-§35',ARRAY['a meeting','a run-in']::text[],'mild'::collision,'teach'::disposition,null,'[[PASTE gloss — ''encounter'' in A Reflection’s voice, ~one line, taught in-breath. AI-prose ban (§17) holds. name the not-authored part.]]',true,ARRAY['lesswrong','ea']::text[],'untested'::gloss_verdict,'a reader who hears only ''conversation'' and misses the not-authored part',null),
  ('valence',ARRAY['valence','valenced']::text[],'transmission','the for-and-against in force; the good-or-bad-for-it that makes anything matter','B1-§53',ARRAY['chemistry/bonding','linguistics']::text[],'mild'::collision,'teach'::disposition,null,'[[PASTE gloss — ''valence'' in A Reflection’s voice, ~one line, taught in-breath. AI-prose ban (§17) holds. the felt for-or-against, not the technical sense.]]',true,'{}'::text[],'untested'::gloss_verdict,'a reader who imports the chemistry sense',null),
  ('stake',ARRAY['stake','stakes']::text[],'transmission','what is at risk in a claim; what makes being wrong cost something','B1-§13',ARRAY['gambling bet','wooden stake','a share/ownership']::text[],'mild'::collision,'teach'::disposition,null,'[[PASTE gloss — ''stake'' in A Reflection’s voice, ~one line, taught in-breath. AI-prose ban (§17) holds. what''s at risk, what wrongness would cost.]]',true,'{}'::text[],'untested'::gloss_verdict,'a reader who hears ''bet'' or ''ownership share''',null),
  ('the-ground',ARRAY['the ground','ground','grounds','grounding']::text[],'transmission','valence as the non-truth-apt floor beneath the truth-apt (§53)','B1-§53',ARRAY['dirt / the floor','reasons/justification','coffee grounds']::text[],'inverts'::collision,'teach'::disposition,null,'[[PASTE gloss — ''the-ground'' in A Reflection’s voice, ~one line, taught in-breath. AI-prose ban (§17) holds. what the whole thing rests on, that isn''t itself true or false.]]',false,'{}'::text[],'untested'::gloss_verdict,'a reader who still hears ''reasons'' or ''foundation-as-argument''',null),
  ('wrongness',ARRAY['wrongness','wrong']::text[],'transmission','being-wrong as a structured condition (stake, one-way settlement, detection-independence, bearing)','B1-§13',ARRAY['being incorrect (flat)','moral wrong']::text[],'none'::collision,'teach'::disposition,null,'[[PASTE gloss — ''wrongness'' in A Reflection’s voice, ~one line, taught in-breath. AI-prose ban (§17) holds. the richer cousin of falsehood.]]',false,'{}'::text[],'untested'::gloss_verdict,'a reader who flattens it to ''incorrect''',null),
  ('mattering',ARRAY['matter','mattering','does it matter']::text[],'transmission','a stake borne by someone; the question of who bears the cost','B1-§53',ARRAY['importance (vague)']::text[],'none'::collision,'teach'::disposition,null,'[[PASTE gloss — ''mattering'' in A Reflection’s voice, ~one line, taught in-breath. AI-prose ban (§17) holds. a stake, and a stake is borne by someone.]]',false,'{}'::text[],'untested'::gloss_verdict,'a reader who keeps it vague/importance-in-general',null),
  ('the-other',ARRAY['the other','the other person']::text[],'transmission','what you did not author, that pushes back; structurally required to settle anything','B1-§30',ARRAY['another person (flat)','othering / out-group']::text[],'inverts'::collision,'teach'::disposition,null,'[[PASTE gloss — ''the-other'' in A Reflection’s voice, ~one line, taught in-breath. AI-prose ban (§17) holds. the part you did not write, pushing back.]]',false,'{}'::text[],'untested'::gloss_verdict,'a reader who hears only ''other people'' or ''othering''',null),
  ('residue',ARRAY['residue']::text[],'transmission','what is deposited and persists across change; the permanent trace','B1-§36',ARRAY['leftover','chemical residue']::text[],'mild'::collision,'teach'::disposition,null,'[[PASTE gloss — ''residue'' in A Reflection’s voice, ~one line, taught in-breath. AI-prose ban (§17) holds. what stays after; the deposit that doesn''t move back.]]',true,'{}'::text[],'untested'::gloss_verdict,'a reader who hears only ''leftover''',null),
  ('holds',ARRAY['holds','hold','held']::text[],'transmission','withstands the pressure of the other; truth = what holds (§43)','B1-§43',ARRAY['physically grasping','holding an opinion']::text[],'mild'::collision,'teach'::disposition,null,'[[PASTE gloss — ''holds'' in A Reflection’s voice, ~one line, taught in-breath. AI-prose ban (§17) holds. withstands pressure, doesn''t shrink under the other.]]',false,'{}'::text[],'untested'::gloss_verdict,'a reader who hears ''grip'' or ''mere opinion''',null),
  ('severing',ARRAY['severing','severs','training-on-descriptions']::text[],'transmission','training on descriptions of states severs signal-from-state, the weld the wedge turns on','IT-6',ARRAY['cutting (generic)']::text[],'none'::collision,'teach'::disposition,null,'[[PASTE gloss — ''severing'' in A Reflection’s voice, ~one line, taught in-breath. AI-prose ban (§17) holds. the one move that makes behavior stop being evidence.]]',false,ARRAY['lesswrong','ea']::text[],'untested'::gloss_verdict,'a reader who misses why the AI case differs from the bat',null),
  ('the-wall-it-invites',ARRAY['the wall it invites','the wall','refuter']::text[],'transmission','what an opponent must DO to break a claim',null,ARRAY['a barrier (generic)','limitation/caveat']::text[],'none'::collision,'teach'::disposition,null,'[[PASTE gloss — ''the-wall-it-invites'' in A Reflection’s voice, ~one line, taught in-breath. AI-prose ban (§17) holds. the move that would break this.]]',false,ARRAY['lesswrong','ea']::text[],'untested'::gloss_verdict,'a reader who reads it as a hedge/caveat',null),
  ('carried-vs-derived',ARRAY['carried','derived','carried, not derived']::text[],'transmission','verdict provenance: carried = inherited/internal; derived = earned by an external encounter',null,ARRAY['delivered/transported','verified (loose)']::text[],'mild'::collision,'teach'::disposition,null,'[[PASTE gloss — ''carried-vs-derived'' in A Reflection’s voice, ~one line, taught in-breath. AI-prose ban (§17) holds. not settled from inside; only an outside encounter settles it.]]',false,'{}'::text[],'untested'::gloss_verdict,'a reader who hears ''verified'' and assumes it''s proven',null),
  ('continuation',ARRAY['continuation','continuations']::text[],'system','an A-layer reader-facing thread',null,ARRAY['a serialized installment','to-be-continued']::text[],'mild'::collision,'demote'::disposition,'keep reading from here',null,true,'{}'::text[],'untested'::gloss_verdict,null,'n/a (label, not prose-bound)'),
  ('the-spine',ARRAY['the spine','live spine','spine']::text[],'system','the live core of continuations',null,ARRAY['book spine','backbone']::text[],'inverts'::collision,'demote'::disposition,'the rest of the writing',null,true,'{}'::text[],'untested'::gloss_verdict,null,'n/a (label, not prose-bound)'),
  ('construction',ARRAY['construction','constructions']::text[],'system','a B-layer formal grounding (proof/section)',null,ARRAY['building site']::text[],'inverts'::collision,'demote'::disposition,'the rigorous version underneath',null,true,'{}'::text[],'untested'::gloss_verdict,null,'n/a (label, not prose-bound)'),
  ('pulls-toward',ARRAY['pulls toward','pulls to']::text[],'system','the soft grounding/significance edge',null,ARRAY['gravity/attraction (mystical)']::text[],'mild'::collision,'demote'::disposition,'connects to',null,true,'{}'::text[],'untested'::gloss_verdict,null,'n/a (label, not prose-bound)'),
  ('leads-to',ARRAY['leads to']::text[],'system','the computed reverse dependency',null,ARRAY['causes / results in']::text[],'none'::collision,'demote'::disposition,'what builds on this',null,true,'{}'::text[],'untested'::gloss_verdict,null,'n/a (label, not prose-bound)'),
  ('wing',ARRAY['wing','entering wing']::text[],'system','a content domain / area of the corpus',null,ARRAY['building wing','bird wing']::text[],'inverts'::collision,'demote'::disposition,'area',null,true,'{}'::text[],'untested'::gloss_verdict,null,'n/a (label, not prose-bound)'),
  ('rests_on',ARRAY['rests_on','rests on']::text[],'system','construction dependency (depends_on)',null,ARRAY['raw machine handle']::text[],'inverts'::collision,'experience'::disposition,null,null,true,'{}'::text[],'untested'::gloss_verdict,null,'reader experiences the thing; never reads the word · never surfaced on a reader surface'),
  ('frontier',ARRAY['frontier']::text[],'system','a node nothing yet builds on',null,ARRAY['raw machine handle']::text[],'inverts'::collision,'experience'::disposition,null,null,true,'{}'::text[],'untested'::gloss_verdict,null,'reader experiences the thing; never reads the word · never surfaced on a reader surface'),
  ('membrane',ARRAY['membrane']::text[],'system','the construction showing through prose',null,ARRAY['raw machine handle']::text[],'inverts'::collision,'experience'::disposition,null,null,true,'{}'::text[],'untested'::gloss_verdict,null,'reader experiences the thing; never reads the word · never surfaced on a reader surface'),
  ('stage',ARRAY['stage','captured','in_protocol','verdict_in']::text[],'system','the status machine',null,ARRAY['raw machine handle']::text[],'inverts'::collision,'experience'::disposition,null,null,true,'{}'::text[],'untested'::gloss_verdict,null,'reader experiences the thing; never reads the word · never surfaced on a reader surface'),
  ('load',ARRAY['load','structural load','depth','dependents']::text[],'system','the engine weight/depth',null,ARRAY['raw machine handle']::text[],'inverts'::collision,'experience'::disposition,null,null,true,'{}'::text[],'untested'::gloss_verdict,null,'reader experiences the thing; never reads the word · never surfaced on a reader surface'),
  ('seal-risk',ARRAY['seal-risk','the open column']::text[],'system','the firewall/openness telemetry',null,ARRAY['raw machine handle']::text[],'inverts'::collision,'experience'::disposition,null,null,true,'{}'::text[],'untested'::gloss_verdict,null,'reader experiences the thing; never reads the word · never surfaced on a reader surface'),
  ('unlock','{}'::text[],'system','(forbidden) gamified retail register; off-constitution',null,'{}'::text[],'none'::collision,'banned'::disposition,null,null,false,'{}'::text[],'untested'::gloss_verdict,null,'say_instead: open · build lint fails on any surface use'),
  ('engagement','{}'::text[],'system','(forbidden) engagement-optimization removes the exit (IT-3, IT-8)',null,'{}'::text[],'none'::collision,'banned'::disposition,null,null,false,'{}'::text[],'untested'::gloss_verdict,null,'say_instead: (do not motivate by retention at all) · build lint fails on any surface use'),
  ('complete / finished / done / settled / 100%','{}'::text[],'system','(forbidden) nothing completes (§47/§59)',null,'{}'::text[],'none'::collision,'banned'::disposition,null,null,false,'{}'::text[],'untested'::gloss_verdict,null,'say_instead: open · in force · captured · build lint fails on any surface use'),
  ('delete (of content)','{}'::text[],'system','(forbidden) content is never removable; residue (§36)',null,'{}'::text[],'none'::collision,'banned'::disposition,null,null,false,'{}'::text[],'untested'::gloss_verdict,null,'say_instead: leave · depart · keep (remove applies only to conduct) · build lint fails on any surface use'),
  ('streak / notification-bait','{}'::text[],'system','(forbidden) retention mechanics the constitution forbids',null,'{}'::text[],'none'::collision,'banned'::disposition,null,null,false,'{}'::text[],'untested'::gloss_verdict,null,'say_instead: (nothing) · build lint fails on any surface use')
on conflict (term) do update set
  surface_forms=excluded.surface_forms, register=excluded.register, our_meaning=excluded.our_meaning,
  defines_node=excluded.defines_node, reader_assumptions=excluded.reader_assumptions,
  collision=excluded.collision, disposition=excluded.disposition,
  plain=coalesce(term.plain, excluded.plain),
  first_gloss=coalesce(term.first_gloss, excluded.first_gloss),
  tier0=excluded.tier0, arrival_early=excluded.arrival_early,
  gloss_verdict=excluded.gloss_verdict, gloss_refuter=excluded.gloss_refuter, notes=excluded.notes;

-- the §B requires-DAG (acyclic; the term firewall validates each edge)
insert into term_edge (from_term,to_term,kind) values
  ('the-ground','valence','requires'),
  ('the-ground','stake','requires'),
  ('wrongness','stake','requires'),
  ('mattering','valence','requires'),
  ('mattering','stake','requires'),
  ('the-other','encounter','requires'),
  ('holds','wrongness','requires'),
  ('carried-vs-derived','encounter','requires')
on conflict (from_term,to_term,kind) do nothing;

commit;
